import Navbar from '@/components/navbar/Navbar';
import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google';
import SignupModal from '@/components/modal/SignupModal';
import ToastProvider from '@/lib/ToastProvider';
import getUser from '@/lib/getUser';


const font=Nunito({subsets:['latin']});

export const metadata: Metadata = {
  title: 'Airbnb',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const user= await getUser();
  
  return (
    <html lang="en">
      <body className={font.className}>
        <ToastProvider />
        <Navbar user={user}/>
        <div className="pb-20 pt-28">

        {children}
        </div>
        </body>
    </html>
  )
}
